id: P010532
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD53257
  title: རང་གཤིས་གདུང་འབོད།
  author: ''
  volumes:
    7989311f0c4e42209933996f2960e0a8:
      image_group_id: I1KG22993
      title: ''
      volume_number: 1
      total_pages: 232
      base_file: v001.txt
